# helm/echo/templates/cluster-issuer.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.ingress.clusterIssuerName }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.ingress.email }}
    privateKeySecretRef:
      name: {{ .Values.ingress.clusterIssuerName }}
    solvers:
    - http01:
        ingress:
          class: {{ .Values.ingress.className }}