apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-neo4j
  labels:
    app: echo
    component: neo4j
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: echo
      component: neo4j
  template:
    metadata:
      labels:
        app: echo
        component: neo4j
    spec:
      containers:
        - name: neo4j
          image: "{{ .Values.neo4j.image.repository }}:{{ .Values.neo4j.image.tag | default "5.18.0-community" }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7474
              name: http
            - containerPort: 7687
              name: bolt
          env:
            - name: NEO4J_AUTH
              value: "neo4j/{{ .Values.neo4j.password }}"
            - name: NEO4J_ACCEPT_LICENSE_AGREEMENT
              value: "yes"
            - name: NEO4J_server_memory_pagecache_size
              value: "{{ .Values.neo4j.config.pagecacheSize | default "512M" }}"
            - name: NEO4J_server_memory_heap_initial__size
              value: "{{ default (default "512M" .Values.neo4j.config.heapSize) .Values.neo4j.config.heapInitialSize }}"
            - name: NEO4J_server_memory_heap_max__size
              value: "{{ default (default "512M" .Values.neo4j.config.heapSize) .Values.neo4j.config.heapMaxSize }}"
            - name: NEO4J_server_bolt_listen__address
              value: "0.0.0.0:7687"
          volumeMounts:
            - name: neo4j-data
              mountPath: /data
          resources:
            requests:
              cpu: "{{ .Values.neo4j.resources.requests.cpu | default "500m" }}"
              memory: "{{ .Values.neo4j.resources.requests.memory | default "1Gi" }}"
            limits:
              cpu: "{{ .Values.neo4j.resources.limits.cpu | default "1000m" }}"
              memory: "{{ .Values.neo4j.resources.limits.memory | default "2Gi" }}"
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -lc
                - 'echo "RETURN 1;" | /var/lib/neo4j/bin/cypher-shell -a bolt://localhost:7687 -u neo4j -p "$NEO4J_PASSWORD" >/dev/null'
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -lc
                - 'echo "RETURN 1;" | /var/lib/neo4j/bin/cypher-shell -a bolt://localhost:7687 -u neo4j -p "$NEO4J_PASSWORD" >/dev/null'
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: neo4j-data
          persistentVolumeClaim:
            claimName: neo4j-data 