apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-worker-cpu
  labels:
    app: echo
    component: worker-cpu
spec:
  replicas: {{ .Values.workerCpu.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  selector:
    matchLabels:
      app: echo
      component: worker-cpu
  template:
    metadata:
      labels:
        app: echo
        component: worker-cpu
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
    spec:
      imagePullSecrets:
        - name: do-registry-secret
      containers:
        - name: worker-cpu
          image: {{ printf "%s/%s:%s" .Values.global.registry .Values.workerCpu.image.repository .Values.global.imageTag | quote }}
          imagePullPolicy: Always
          terminationGracePeriodSeconds: 120
          command:
            - '/bin/sh'
            - '/code/server/prod-worker-cpu.sh'
          env:
            - name: ENABLE_CHAT_AUTO_SELECT
              value: {{ .Values.apiServer.env.ENABLE_CHAT_AUTO_SELECT | quote }}

            - name: ENABLE_AUDIO_LIGHTRAG_INPUT
              value: {{ .Values.apiServer.env.ENABLE_AUDIO_LIGHTRAG_INPUT | quote }}

            - name: DEBUG_MODE
              value: {{ .Values.apiServer.env.DEBUG_MODE | quote }}

            - name: DIRECTUS_BASE_URL
              value: {{ .Values.apiServer.env.DIRECTUS_BASE_URL | quote }}

            - name: DIRECTUS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: echo-backend-secrets
                  key: DIRECTUS_ADMIN_TOKEN

            - name: DIRECTUS_SECRET
              valueFrom:
                secretKeyRef:
                  name: echo-backend-secrets
                  key: DIRECTUS_SECRET

            - name: DIRECTUS_SESSION_COOKIE_NAME
              value: {{ .Values.directus.env.SESSION_COOKIE_NAME | quote }}

            - name: ADMIN_BASE_URL
              value: {{ .Values.apiServer.env.ADMIN_BASE_URL | quote }}

            - name: PARTICIPANT_BASE_URL
              value: {{ .Values.apiServer.env.PARTICIPANT_BASE_URL | quote }}

            - name: BUILD_VERSION
              value: {{ .Values.apiServer.env.BUILD_VERSION | quote }}

            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: echo-backend-secrets
                  key: OPENAI_API_KEY

            - name: ANTHROPIC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: echo-backend-secrets
                  key: ANTHROPIC_API_KEY

            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: echo-backend-secrets
                  key: REDIS_URL

            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: echo-backend-secrets
                  key: DATABASE_URL
            
            # Neo4j Configuration
            - name: NEO4J_URI
              value: {{ .Values.apiServer.env.NEO4J_URI | default "bolt://echo-neo4j:7687" | quote }}
            
            - name: NEO4J_USERNAME
              value: {{ .Values.apiServer.env.NEO4J_USERNAME | default "neo4j" | quote }}
            
            - name: NEO4J_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: echo-backend-secrets
                  key: NEO4J_PASSWORD
            
            - name: DISABLE_CORS
              value: {{ .Values.apiServer.env.DISABLE_CORS | quote }}

            - name: DISABLE_REDACTION
              value: {{ .Values.apiServer.env.DISABLE_REDACTION | quote }}

            - name: DISABLE_SENTRY
              value: {{ .Values.apiServer.env.DISABLE_SENTRY | quote }}

            - name: SERVE_API_DOCS
              value: {{ .Values.apiServer.env.SERVE_API_DOCS | quote }}

            - name: STORAGE_S3_REGION
              value: {{ .Values.apiServer.env.STORAGE_S3_REGION | quote }}

            - name: STORAGE_S3_ENDPOINT
              value: {{ .Values.apiServer.env.STORAGE_S3_ENDPOINT | quote }}
            
            - name: STORAGE_S3_BUCKET
              value: {{ .Values.apiServer.env.STORAGE_S3_BUCKET | quote }}
            
            - name: STORAGE_S3_KEY
              valueFrom:
                secretKeyRef:
                  name: echo-backend-secrets
                  key: S3_ACCESS_KEY

            - name: STORAGE_S3_SECRET
              valueFrom:
                secretKeyRef:
                  name: echo-backend-secrets
                  key: S3_SECRET_KEY
                  
            # LightRAG LiteLLM Configuration
            - name: LIGHTRAG_LITELLM_INFERENCE_MODEL
              valueFrom:
                secretKeyRef:
                  name: echo-backend-secrets
                  key: LIGHTRAG_LITELLM_INFERENCE_MODEL
            
            - name: LIGHTRAG_LITELLM_INFERENCE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: echo-backend-secrets
                  key: LIGHTRAG_LITELLM_INFERENCE_API_KEY

            - name: LIGHTRAG_LITELLM_EMBEDDING_API_VERSION
              valueFrom:
                secretKeyRef:
                  name: echo-backend-secrets
                  key: LIGHTRAG_LITELLM_EMBEDDING_API_VERSION

            - name: LIGHTRAG_LITELLM_EMBEDDING_API_KEY
              valueFrom:
                secretKeyRef:
                  name: echo-backend-secrets
                  key: LIGHTRAG_LITELLM_EMBEDDING_API_KEY

            - name: LIGHTRAG_LITELLM_EMBEDDING_API_BASE
              valueFrom:
                secretKeyRef:
                  name: echo-backend-secrets
                  key: LIGHTRAG_LITELLM_EMBEDDING_API_BASE

            - name: LIGHTRAG_LITELLM_EMBEDDING_MODEL
              valueFrom:
                secretKeyRef:
                  name: echo-backend-secrets
                  key: LIGHTRAG_LITELLM_EMBEDDING_MODEL

            - name: LIGHTRAG_LITELLM_TEXTSTRUCTUREMODEL_API_BASE
              valueFrom:
                secretKeyRef:
                  name: echo-backend-secrets
                  key: LIGHTRAG_LITELLM_TEXTSTRUCTUREMODEL_API_BASE

            - name: LIGHTRAG_LITELLM_TEXTSTRUCTUREMODEL_API_VERSION
              valueFrom:
                secretKeyRef:
                  name: echo-backend-secrets
                  key: LIGHTRAG_LITELLM_TEXTSTRUCTUREMODEL_API_VERSION

            - name: LIGHTRAG_LITELLM_TEXTSTRUCTUREMODEL_API_KEY
              valueFrom:
                secretKeyRef:
                  name: echo-backend-secrets
                  key: LIGHTRAG_LITELLM_TEXTSTRUCTUREMODEL_API_KEY

            - name: LIGHTRAG_LITELLM_TEXTSTRUCTUREMODEL_MODEL
              valueFrom:
                secretKeyRef:
                  name: echo-backend-secrets
                  key: LIGHTRAG_LITELLM_TEXTSTRUCTUREMODEL_MODEL

            - name: LIGHTRAG_LITELLM_AUDIOMODEL_API_BASE
              valueFrom:
                secretKeyRef:
                  name: echo-backend-secrets
                  key: LIGHTRAG_LITELLM_AUDIOMODEL_API_BASE

            - name: LIGHTRAG_LITELLM_AUDIOMODEL_API_VERSION
              valueFrom:
                secretKeyRef:
                  name: echo-backend-secrets
                  key: LIGHTRAG_LITELLM_AUDIOMODEL_API_VERSION

            - name: LIGHTRAG_LITELLM_AUDIOMODEL_API_KEY
              valueFrom:
                secretKeyRef:
                  name: echo-backend-secrets
                  key: LIGHTRAG_LITELLM_AUDIOMODEL_API_KEY

            - name: LIGHTRAG_LITELLM_AUDIOMODEL_MODEL
              valueFrom:
                secretKeyRef:
                  name: echo-backend-secrets
                  key: LIGHTRAG_LITELLM_AUDIOMODEL_MODEL

            - name: LIGHTRAG_LITELLM_API_BASE
              valueFrom:
                secretKeyRef:
                  name: echo-backend-secrets
                  key: LIGHTRAG_LITELLM_API_BASE

            - name: LIGHTRAG_LITELLM_API_VERSION
              valueFrom:
                secretKeyRef:
                  name: echo-backend-secrets
                  key: LIGHTRAG_LITELLM_API_VERSION

            - name: LIGHTRAG_LITELLM_API_KEY
              valueFrom:
                secretKeyRef:
                  name: echo-backend-secrets
                  key: LIGHTRAG_LITELLM_API_KEY

            - name: LIGHTRAG_LITELLM_MODEL
              valueFrom:
                secretKeyRef:
                  name: echo-backend-secrets
                  key: LIGHTRAG_LITELLM_MODEL
                  
          resources:
            requests:
              cpu: {{ .Values.workerCpu.resources.requests.cpu | quote }}
              memory: {{ .Values.workerCpu.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.workerCpu.resources.limits.cpu | quote }}
              memory: {{ .Values.workerCpu.resources.limits.memory | quote }} 

          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - python /code/server/prod-worker-readiness.py
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3

          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - python /code/server/prod-worker-liveness.py
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 3
