apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-worker-cpu
  labels:
    app: echo
    component: worker-cpu
spec:
  replicas: {{ .Values.workerCpu.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  selector:
    matchLabels:
      app: echo
      component: worker-cpu
  template:
    metadata:
      labels:
        app: echo
        component: worker-cpu
    spec:
      imagePullSecrets:
        - name: do-registry-secret
      containers:
        - name: worker-cpu
          image: {{ printf "%s/%s:%s" .Values.global.registry .Values.workerCpu.image.repository .Values.global.imageTag | quote }}
          imagePullPolicy: Always
          terminationGracePeriodSeconds: 90
          command:
            - '/bin/sh'
            - '/code/server/prod-worker-cpu.sh'
          ports:
            - containerPort: {{ .Values.apiServer.service.port }}
          env:
            - name: DIRECTUS_BASE_URL
              value: {{ .Values.apiServer.env.DIRECTUS_BASE_URL | quote }}

            - name: DIRECTUS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: echo-backend-secrets
                  key: DIRECTUS_ADMIN_TOKEN

            - name: DIRECTUS_SECRET
              valueFrom:
                secretKeyRef:
                  name: echo-backend-secrets
                  key: DIRECTUS_SECRET

            - name: DIRECTUS_SESSION_COOKIE_NAME
              value: {{ .Values.directus.env.SESSION_COOKIE_NAME | quote }}

            - name: ADMIN_BASE_URL
              value: {{ .Values.apiServer.env.ADMIN_BASE_URL | quote }}

            - name: PARTICIPANT_BASE_URL
              value: {{ .Values.apiServer.env.PARTICIPANT_BASE_URL | quote }}

            - name: BUILD_VERSION
              value: {{ .Values.apiServer.env.BUILD_VERSION | quote }}

            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: echo-backend-secrets
                  key: OPENAI_API_KEY

            - name: ANTHROPIC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: echo-backend-secrets
                  key: ANTHROPIC_API_KEY

            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: echo-backend-secrets
                  key: REDIS_URL

            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: echo-backend-secrets
                  key: DATABASE_URL
                
            - name: DISABLE_CORS
              value: {{ .Values.apiServer.env.DISABLE_CORS | quote }}

            - name: DISABLE_REDACTION
              value: {{ .Values.apiServer.env.DISABLE_REDACTION | quote }}

            - name: DISABLE_SENTRY
              value: {{ .Values.apiServer.env.DISABLE_SENTRY | quote }}

            - name: SERVE_API_DOCS
              value: {{ .Values.apiServer.env.SERVE_API_DOCS | quote }}
            
            - name: STORAGE_S3_REGION
              value: {{ .Values.apiServer.env.STORAGE_S3_REGION | quote }}

            - name: STORAGE_S3_ENDPOINT
              value: {{ .Values.apiServer.env.STORAGE_S3_ENDPOINT | quote }}
            
            - name: STORAGE_S3_BUCKET
              value: {{ .Values.apiServer.env.STORAGE_S3_BUCKET | quote }}
            
            - name: STORAGE_S3_KEY
              valueFrom:
                secretKeyRef:
                  name: echo-backend-secrets
                  key: S3_ACCESS_KEY

            - name: STORAGE_S3_SECRET
              valueFrom:
                secretKeyRef:
                  name: echo-backend-secrets
                  key: S3_SECRET_KEY

          resources:
            requests:
              cpu: {{ .Values.workerCpu.resources.requests.cpu | quote }}
              memory: {{ .Values.workerCpu.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.workerCpu.resources.limits.cpu | quote }}
              memory: {{ .Values.workerCpu.resources.limits.memory | quote }} 

          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - python /code/server/prod-worker-readiness.py
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - python /code/server/prod-worker-liveness.py
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
