apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-worker
  labels:
    app: echo
    component: worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  selector:
    matchLabels:
      app: echo
      component: worker
  template:
    metadata:
      labels:
        app: echo
        component: worker
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
    spec:
      terminationGracePeriodSeconds: 120
      imagePullSecrets:
        - name: do-registry-secret
      containers:
        - name: worker
          image: {{ printf "%s/%s:%s" .Values.global.registry .Values.worker.image.repository .Values.global.imageTag | quote }}
          imagePullPolicy: Always
          command:
            - "/bin/sh"
            - "/code/server/prod-worker.sh"
          env:
{{- include "echo.commonEnvVars" . | nindent 12 }}
{{- include "echo.secretEnvVars" . | nindent 12 }}


          # -----------------------------------
          resources:
            requests:
              cpu: {{ .Values.worker.resources.requests.cpu | quote }}
              memory: {{ .Values.worker.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.worker.resources.limits.cpu | quote }}
              memory: {{ .Values.worker.resources.limits.memory | quote }}
