apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-api
  labels:
    app: echo
    component: api
spec:
  replicas: {{ .Values.apiServer.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.rollout.maxUnavailable | quote }}
      maxSurge: {{ .Values.rollout.maxSurge | quote }}
  selector:
    matchLabels:
      app: echo
      component: api
  template:
    metadata:
      labels:
        app: echo
        component: api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
    spec:
      priorityClassName: echo-high
      terminationGracePeriodSeconds: 60
      imagePullSecrets:
        - name: do-registry-secret
      containers:
        - name: api-server
          image: {{ printf "%s/%s:%s" .Values.global.registry .Values.apiServer.image.repository .Values.global.imageTag | quote }}
          imagePullPolicy: Always
          command:
            - "/bin/sh"
            - "/code/server/prod.sh"
          ports:
            - containerPort: {{ .Values.apiServer.service.port }}
              name: http

          env:
{{- include "echo.commonEnvVars" . | nindent 12 }}
{{- include "echo.secretEnvVars" . | nindent 12 }}

          resources:
            requests:
              cpu: {{ .Values.apiServer.resources.requests.cpu | quote }}
              memory: {{ .Values.apiServer.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.apiServer.resources.limits.cpu | quote }}
              memory: {{ .Values.apiServer.resources.limits.memory | quote }}

          readinessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 15
            successThreshold: 1
            failureThreshold: 3
          
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 15
            failureThreshold: 3
