# deploy/helm/echo/templates/deployment-directus.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-directus
  labels:
    app: echo
    component: directus
spec:
  replicas: {{ .Values.directus.replicaCount }}
  selector:
    matchLabels:
      app: echo
      component: directus
  template:
    metadata:
      labels:
        app: echo
        component: directus
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8055"
    spec:
      imagePullSecrets:
        - name: do-registry-secret
      containers:
        - name: directus
          image: {{ printf "%s/%s:%s" .Values.global.registry .Values.directus.image.repository .Values.global.imageTag | quote }}
          imagePullPolicy: Always
          command:
            - '/bin/sh'
            - '-c'
            - |
              npm run schema apply system-collections; 
              npx directus start;
          ports:
            - containerPort: {{ .Values.directus.service.port }}
              name: http
          env:
            - name: PUBLIC_URL
              value: {{ .Values.directus.env.PUBLIC_URL | quote }}

            - name: PORT
              value: "8055"

            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: echo-backend-secrets
                  key: DIRECTUS_SECRET

            - name: ADMIN_EMAIL
              value: "admin@dembrane.com"

            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: echo-backend-secrets
                  key: DIRECTUS_ADMIN_PASSWORD

            - name: ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: echo-backend-secrets
                  key: DIRECTUS_ADMIN_TOKEN

            - name: WEBSOCKETS_ENABLED
              value: "true"

            - name: DB_CLIENT
              value: "pg"

            - name: DB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: echo-backend-secrets
                  key: DATABASE_URL

            - name: TELEMETRY
              value: "false"

            - name: REDIS_ENABLED
              value: "true"

            - name: REDIS
              valueFrom:
                secretKeyRef:
                  name: echo-backend-secrets
                  key: REDIS_URL

            - name: CORS_ENABLED
              value: "true"

            - name: CORS_ORIGIN
              value: {{ .Values.directus.env.CORS_ORIGIN | quote }}

            - name: CORS_CREDENTIALS
              value: "true"
            
            - name: CORS_METHODS
              value: "GET,POST,PUT,PATCH,DELETE,OPTIONS,SEARCH"

            - name: CORS_ALLOW_HEADERS
              value: "Content-Type,Authorization"
            
            - name: CORS_EXPOSED_HEADERS
              value: "Content-Type,Content-Range,X-Total-Count"
            
            - name: CORS_MAX_AGE
              value: "18000"

            - name: SESSION_COOKIE_NAME
              value: {{ .Values.directus.env.SESSION_COOKIE_NAME | quote }}

            - name: SESSION_COOKIE_DOMAIN
              value: {{ .Values.directus.env.SESSION_COOKIE_DOMAIN | quote }}

            - name: SESSION_COOKIE_SAME_SITE
              value: "lax"

            - name: SESSION_COOKIE_SECURE
              value: "lax"

            - name: EMAIL_TRANSPORT
              value: "smtp"

            - name: EMAIL_FROM
              valueFrom:
                secretKeyRef:
                  name: echo-backend-secrets
                  key: DIRECTUS_EMAIL_FROM

            - name: EMAIL_SMTP_HOST
              valueFrom:
                secretKeyRef:
                  name: echo-backend-secrets
                  key: DIRECTUS_EMAIL_SMTP_HOST

            - name: EMAIL_SMTP_PORT
              valueFrom:
                secretKeyRef:
                  name: echo-backend-secrets
                  key: DIRECTUS_EMAIL_SMTP_PORT

            - name: EMAIL_SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: echo-backend-secrets
                  key: DIRECTUS_EMAIL_SMTP_USER

            - name: EMAIL_SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: echo-backend-secrets
                  key: DIRECTUS_EMAIL_SMTP_PASSWORD
            
            # why this is done? contact @ussama
            - name: EMAIL_SMTP_SECURE
              value: "false"
            
            # why this is done? contact @ussama
            - name: EMAIL_SMTP_IGNORE_TLS
              value: "false"

            - name: USER_REGISTER_URL_ALLOW_LIST
              value: {{ .Values.directus.env.USER_REGISTER_URL_ALLOW_LIST | quote }}

            - name: PASSWORD_RESET_URL_ALLOW_LIST
              value: {{ .Values.directus.env.PASSWORD_RESET_URL_ALLOW_LIST | quote }}

            - name: USER_INVITE_URL_ALLOW_LIST
              value: {{ .Values.directus.env.USER_INVITE_URL_ALLOW_LIST | quote }}

            - name: AUTH_PROVIDERS
              value: "google"

            - name: AUTH_GOOGLE_DRIVER
              value: "openid"

            - name: AUTH_GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: echo-backend-secrets
                  key: AUTH_GOOGLE_CLIENT_ID

            - name: AUTH_GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: echo-backend-secrets
                  key: AUTH_GOOGLE_CLIENT_SECRET

            - name: AUTH_GOOGLE_ISSUER_URL
              value: "https://accounts.google.com"

            - name: AUTH_GOOGLE_IDENTIFIER_KEY
              value: "email"

            - name: AUTH_GOOGLE_FIRST_NAME_KEY
              value: "given_name"

            - name: AUTH_GOOGLE_LAST_NAME_KEY
              value: "family_name"

            - name: AUTH_GOOGLE_ICON
              value: "google"

            - name: AUTH_GOOGLE_LABEL
              value: "Google"

            - name: AUTH_GOOGLE_ALLOW_PUBLIC_REGISTRATION
              value: {{ .Values.directus.env.AUTH_GOOGLE_ALLOW_PUBLIC_REGISTRATION | quote }}

            - name: AUTH_GOOGLE_DEFAULT_ROLE_ID
              value: {{ .Values.directus.env.AUTH_GOOGLE_DEFAULT_ROLE_ID | quote }}

            - name: AUTH_GOOGLE_REDIRECT_ALLOW_LIST
              value: {{ .Values.directus.env.AUTH_GOOGLE_REDIRECT_ALLOW_LIST | quote }}
            
            - name: STORAGE_LOCATIONS
              value: "s3"
            
            - name: STORAGE_S3_DRIVER
              value: "s3"

            - name: STORAGE_S3_KEY
              valueFrom:
                secretKeyRef:
                  name: echo-backend-secrets
                  key: S3_ACCESS_KEY

            - name: STORAGE_S3_SECRET
              valueFrom:
                secretKeyRef:
                  name: echo-backend-secrets
                  key: S3_SECRET_KEY
            
            - name: STORAGE_S3_BUCKET
              value: {{ .Values.directus.env.STORAGE_S3_BUCKET | quote }}
            
            - name: STORAGE_S3_REGION
              value: {{ .Values.directus.env.STORAGE_S3_REGION | quote }}
            
            - name: STORAGE_S3_ENDPOINT
              value: {{ .Values.directus.env.STORAGE_S3_ENDPOINT | quote }}
            
            - name: DB_SSL_REJECT_UNAUTHORIZED
              value: "false"
            
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: "0"
            
            # for flows
            - name: FLOWS_ENV_ALLOW_LIST
              value: "ADMIN_BASE_URL,PARTICIPANT_BASE_URL"
            
            - name: ADMIN_BASE_URL
              value: {{ .Values.apiServer.env.ADMIN_BASE_URL | quote }}
            
            - name: PARTICIPANT_BASE_URL
              value: {{ .Values.apiServer.env.PARTICIPANT_BASE_URL | quote }}

          resources:
            requests:
              cpu: {{ .Values.directus.resources.requests.cpu | quote }}
              memory: {{ .Values.directus.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.directus.resources.limits.cpu | quote }}
              memory: {{ .Values.directus.resources.limits.memory | quote }}
