apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: echo-worker-scheduler-hpa
  labels:
    app: echo
    component: worker-scheduler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: echo-worker-scheduler
  minReplicas: {{ .Values.workerScheduler.replicaCount }}
  maxReplicas: {{ .Values.workerScheduler.maxReplicaCount }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
    scaleUp:
      stabilizationWindowSeconds: 60 