apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: echo-worker-cpu-hpa
  labels:
    app: echo
    component: worker-cpu-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: echo-worker-cpu
  minReplicas: {{ .Values.workerCpu.replicaCount }}
  maxReplicas: {{ .Values.workerCpu.maxReplicaCount }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
    scaleUp:
      stabilizationWindowSeconds: 60 