apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: echo-api-hpa
  labels:
    app: echo
    component: api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: echo-api
  minReplicas: {{ .Values.apiServer.replicaCount }}
  maxReplicas: {{ .Values.apiServer.maxReplicaCount }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
    scaleUp:
      stabilizationWindowSeconds: 60 