apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: echo-directus-hpa
  labels:
    app: echo
    component: directus-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: echo-directus
  minReplicas: {{ .Values.directus.replicaCount }}
  maxReplicas: {{ .Values.directus.maxReplicaCount }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
    scaleUp:
      stabilizationWindowSeconds: 60 