apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: echo-directus-pdb
  labels:
    app: echo
    component: directus
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: echo
      component: directus
  unhealthyPodEvictionPolicy: AlwaysAllow 