apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: echo-low
  labels:
    app: echo
value: 1000
globalDefault: false
preemptionPolicy: PreemptLowerPriority
description: "Low priority for workers - can be preempted for higher priority workloads"
