apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-data
  labels:
    app: echo
    component: neo4j
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.neo4j.storage.size | default "10Gi" }}
  storageClassName: {{ .Values.storage.storageClassName | default "do-block-storage" }} 