apiVersion: v1
kind: Service
metadata:
  name: echo-neo4j
  labels:
    app: echo
    component: neo4j
spec:
  ports:
    - port: 7474
      targetPort: 7474
      name: http
    - port: 7687
      targetPort: 7687
      name: bolt
  selector:
    app: echo
    component: neo4j 