# Configuration for the monitoring stack
clusterIssuerName: "letsencrypt-prod"
domain: "echo-next.dembrane.com"  # Default domain for development

# Basic auth for monitoring ingress - will be overridden by SealedSecret
basicAuthValue: "admin:$apr1$z9Tl9AAN$WLoDGwQTFU7GULw05NVqk."

# Storage settings
storage:
  storageClassName: "do-block-storage"
  prometheus:
    size: "10Gi"
  loki:
    size: "20Gi"
  grafana:
    size: "5Gi"

# Prometheus settings
prometheus:
  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"

# Grafana settings
grafana:
  adminPassword: "admin"  # Override this with values-prod.yaml or --set
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "300m"
      memory: "512Mi"

# Loki settings
loki:
  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"

# Promtail settings
promtail:
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"

# Ingress settings
ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  basicAuth:
    enabled: true