apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: echo-monitoring-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dembrane/echo-gitops.git
    targetRevision: feature/monitoring_prod
    path: helm/monitoring
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 