global:
  imageTag: "5184a605c81e7996e5d316e7a359233e46e577ec"
  registry: "registry.digitalocean.com/dbr-cr"

directus:
  replicaCount: 1
  maxReplicaCount: 1
  image:
    repository: "dbr-echo-directus"
  service:
    port: 8055
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "1Gi"
  env:
    PUBLIC_URL: "https://directus.echo-next.dembrane.com"
    CORS_ORIGIN: "https://dashboard.echo-next.dembrane.com,https://portal.echo-next.dembrane.com,http://localhost:5173,http://localhost:5174"
    SESSION_COOKIE_NAME: "dembrane_session_token_dev"
    SESSION_COOKIE_DOMAIN: "echo-next.dembrane.com"
    USER_REGISTER_URL_ALLOW_LIST: "https://dashboard.echo-next.dembrane.com/verify-email,http://localhost:5173/verify-email"
    PASSWORD_RESET_URL_ALLOW_LIST: "https://dashboard.echo-next.dembrane.com/password-reset,http://localhost:5173/password-reset"
    USER_INVITE_URL_ALLOW_LIST: "https://dashboard.echo-next.dembrane.com/invite,http://localhost:5173/invite"
    AUTH_GOOGLE_ALLOW_PUBLIC_REGISTRATION: "false"
    AUTH_GOOGLE_DEFAULT_ROLE_ID: 2446660a-ab6c-4801-ad69-5711030cba83
    AUTH_GOOGLE_REDIRECT_ALLOW_LIST: "https://dashboard.echo-next.dembrane.com/en-US/projects,https://dashboard.echo-next.dembrane.com/nl-NL/projects,https://dashboard.echo-next.dembrane.com/es-ES/projects,https://dashboard.echo-next.dembrane.com/fr-FR/projects,https://dashboard.echo-next.dembrane.com/de-DE/projects"
    # dummy for compat of DO with S3
    STORAGE_S3_REGION: "us-east-1"
    STORAGE_S3_ENDPOINT: "https://ams3.digitaloceanspaces.com"
    STORAGE_S3_BUCKET: "dbr-echo-dev-uploads"

apiServer:
  replicaCount: 2
  maxReplicaCount: 2
  image:
    repository: "dbr-echo-server"
  service:
    port: 8000
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "1Gi"
  env:
    DEBUG_MODE: "1"
    ENABLE_CHAT_AUTO_SELECT: "1"
    ENABLE_AUDIO_LIGHTRAG_INPUT: "1"
    DISABLE_CORS: "0"
    DISABLE_REDACTION: "1"
    DISABLE_SENTRY: "0"
    SERVE_API_DOCS: "1"
    DIRECTUS_BASE_URL: "https://directus.echo-next.dembrane.com"
    ADMIN_BASE_URL: "https://dashboard.echo-next.dembrane.com"
    PARTICIPANT_BASE_URL: "https://portal.echo-next.dembrane.com"
    NEO4J_URI: "bolt://echo-neo4j:7687"
    NEO4J_USERNAME: "neo4j"
    STORAGE_S3_REGION: "us-east-1"
    STORAGE_S3_ENDPOINT: "https://ams3.digitaloceanspaces.com"
    STORAGE_S3_BUCKET: "dbr-echo-dev-uploads"

worker:
  # the deployment uses the same tags as the api server
  # only the command is different
  replicaCount: 1
  maxReplicaCount: 1
  image:
    repository: "dbr-echo-server"
  resources:
    requests:
      cpu: "500m"
      memory: "800Mi"
    limits:
      cpu: "1"
      memory: "1536Mi"

workerCpu:
  replicaCount: 1
  maxReplicaCount: 2
  image:
    repository: "dbr-echo-server"
  resources:
    requests:
      cpu: "1"
      memory: "1Gi"
    limits:
      cpu: "2"
      memory: "2Gi"
  
workerScheduler:
  replicaCount: 1
  maxReplicaCount: 1
  image:
    repository: "dbr-echo-server"
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "800m"
      memory: "1Gi"

neo4j:
  image:
    repository: "neo4j"
    tag: "5.18.0-community"
  password: "admin@dembrane"
  storage:
    size: "10Gi"
  config:
    pagecacheSize: "512M"
    heapSize: "512M"
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"

ingress:
  enabled: true
  className: "nginx"
  email: "admin@dembrane.com"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  clusterIssuerName: "letsencrypt-prod"
  domain: "echo-next.dembrane.com"
  hosts:
    directus: "directus.echo-next.dembrane.com"
    api: "api.echo-next.dembrane.com"
  tls:
    - secretName: "echo-next-tls"
      hosts:
        - "directus.echo-next.dembrane.com"
        - "api.echo-next.dembrane.com"

storage:
  storageClassName: "do-block-storage"
