global:
  imageTag: "d66c5911aaaa55c1fc018bfd247b4ce58eed2f4d"
  registry: "registry.digitalocean.com/dbr-cr"

directus:
  replicaCount: 1
  maxReplicaCount: 2
  image:
    repository: "dbr-echo-directus"
  service:
    port: 8055
  resources:
    requests:
      cpu: "300m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "768Mi"
  env:
    PUBLIC_URL: "https://directus.echo-next.dembrane.eu"
    # ADMIN_PASSWORD: 
    # ADMIN_TOKEN:
    # DB_CONNECTION_STRING:
    # REDIS:
    CORS_ORIGIN: "https://dashboard.echo-next.dembrane.eu,https://portal.echo-next.dembrane.eu"
    SESSION_COOKIE_NAME: "dembrane_session_token_dev"
    SESSION_COOKIE_DOMAIN: "echo-next.dembrane.eu"
    # EMAIL_FROM
    # EMAIL_SMTP_HOST
    # EMAIL_SMTP_PORT
    # EMAIL_SMTP_USER
    # EMAIL_SMTP_PASSWORD
    USER_REGISTER_URL_ALLOW_LIST: "https://dashboard.echo-next.dembrane.eu/verify-email"
    PASSWORD_RESET_URL_ALLOW_LIST: "https://dashboard.echo-next.dembrane.eu/password-reset"
    USER_INVITE_URL_ALLOW_LIST: "https://dashboard.echo-next.dembrane.eu/invite"
    # AUTH_GOOGLE_CLIENT_ID
    # AUTH_GOOGLE_CLIENT_SECRET
    AUTH_GOOGLE_ALLOW_PUBLIC_REGISTRATION: "true"
    AUTH_GOOGLE_DEFAULT_ROLE_ID: 2446660a-ab6c-4801-ad69-5711030cba83
    AUTH_GOOGLE_REDIRECT_ALLOW_LIST: "https://dashboard.echo-next.dembrane.eu/en-US/projects,https://dashboard.echo-next.dembrane.eu/nl-NL/projects,https://dashboard.echo-next.dembrane.eu/es-ES/projects,https://dashboard.echo-next.dembrane.eu/fr-FR/projects,https://dashboard.echo-next.dembrane.eu/de-DE/projects"
    # STORAGE_S3_KEY
    # STORAGE_S3_SECRET
    # dummy for compat of DO with S3
    STORAGE_S3_REGION: "us-east-1"
    STORAGE_S3_ENDPOINT: "https://ams3.digitaloceanspaces.com"
    STORAGE_S3_BUCKET: "dbr-echo-dev-uploads"

apiServer:
  replicaCount: 1
  maxReplicaCount: 2
  image:
    repository: "dbr-echo-server"
  service:
    port: 8000
  resources:
    requests:
      cpu: "300m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "800Mi"
  env:
    DEBUG_MODE: "1"
    DIRECTUS_BASE_URL: "https://directus.echo-next.dembrane.eu"
    # DIRECTUS_TOKEN:
    # DIRECTUS_SECRET:
    ADMIN_BASE_URL: "https://dashboard.echo-next.dembrane.eu"
    PARTICIPANT_BASE_URL: "https://portal.echo-next.dembrane.eu"
    # OPENAI_API_KEY:
    # ANTHROPIC_API_KEY:
    # REDIS_URL:
    # DATABASE_URL:
    DISABLE_CORS: "0"
    DISABLE_REDACTION: "1"
    DISABLE_SENTRY: "0"
    SERVE_API_DOCS: "1"
    # S3_ACCESS_KEY
    # S3_SECRET_KEY
    # dummy for compat of DO with S3
    STORAGE_S3_REGION: "us-east-1"
    STORAGE_S3_ENDPOINT: "https://ams3.digitaloceanspaces.com"
    STORAGE_S3_BUCKET: "dbr-echo-dev-uploads"

worker:
  # the deployment uses the same tags as the api server
  # only the command is different
  replicaCount: 1
  maxReplicaCount: 2
  image:
    repository: "dbr-echo-server"
  resources:
    requests:
      cpu: "300m"
      memory: "800Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"

ingress:
  enabled: true
  className: "nginx"
  email: "admin@dembrane.com"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  clusterIssuerName: "letsencrypt-prod"
  hosts:
    directus: "directus.echo-next.dembrane.eu"
    api: "api.echo-next.dembrane.eu"
  tls:
    - secretName: "echo-next-tls"
      hosts:
        - "directus.echo-next.dembrane.eu"
        - "api.echo-next.dembrane.eu"
