apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname','service']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 2h
      receiver: 'slack-prod'
    receivers:
      - name: 'slack-prod'
        slack_configs:
          - api_url: ${SLACK_WEBHOOK}
            channel: '#prod-alerts'
            send_resolved: true
            title: '[{{ `{{` }} .Status {{ `}}` }}] {{ `{{` }} .CommonLabels.alertname {{ `}}` }}'
            text: >-
              *Alert:* {{ `{{` }} .CommonLabels.alertname {{ `}}` }}\n
              *Severity:* {{ `{{` }} .CommonLabels.severity {{ `}}` }}\n
              *Description:* {{ `{{` }} .CommonAnnotations.description {{ `}}` }}\n
              *Details:* {{ `{{` }} .CommonLabels {{ `}}` }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: monitoring
  labels:
    app: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
        - name: alertmanager
          image: prom/alertmanager:v0.26.0
          args:
            - '--config.file=/etc/alertmanager/alertmanager.yml'
            - '--storage.path=/alertmanager'
          ports:
            - name: http
              containerPort: 9093
          env:
            - name: SLACK_WEBHOOK
              valueFrom:
                secretKeyRef:
                  name: monitoring-secrets
                  key: slack-webhook-url
          volumeMounts:
            - name: alertmanager-config
              mountPath: /etc/alertmanager/alertmanager.yml
              subPath: alertmanager.yml
      volumes:
        - name: alertmanager-config
          configMap:
            name: alertmanager-config
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: monitoring
  labels:
    app: alertmanager
spec:
  selector:
    app: alertmanager
  ports:
    - name: http
      port: 9093
      targetPort: http


