apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: monitoring
data:
  loki.yaml: |
    auth_enabled: false

    server:
      http_listen_port: 3100

    common:
      path_prefix: /data
      storage:
        filesystem:
          chunks_directory: /data/chunks
          rules_directory: /data/rules
      ring:
        kvstore:
          store: inmemory

    schema_config:
      configs:
        - from: 2022-01-01
          store: tsdb
          object_store: filesystem
          schema: v12
          index:
            prefix: index_
            period: 24h

    storage:
      type: filesystem
      filesystem:
        directory: /data/chunks

    limits_config:
      retention_period: 7d
      ingestion_rate_mb: 10
      ingestion_burst_size_mb: 20
      max_query_length: 12h
      max_query_parallelism: 32
      max_streams_per_user: 10000
      max_global_streams_per_user: 10000

    ruler:
      storage:
        type: local
        local:
          directory: /data/rules
      rule_path: /tmp/rules
      ring:
        kvstore:
          store: inmemory
      enable_api: true

    analytics:
      reporting_enabled: false 