apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: monitoring
data:
  promtail.yaml: |
    server:
      http_listen_port: 3101
      grpc_listen_port: 0
    
    positions:
      filename: /run/promtail/positions.yaml

    clients:
      - url: http://loki:3100/loki/api/v1/push

    scrape_configs:
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
        pipeline_stages:
          - docker: {}
          - cri: {}
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_controller_name]
            regex: ([0-9a-z-.]+)(-[0-9a-f]{8,10})?
            action: replace
            target_label: __tmp_controller_name
          # Set a stable 'app' label preferring app.kubernetes.io/name, then app, then controller name
          - action: replace
            source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
            target_label: app
            regex: (.+)
            replacement: $1
          - action: replace
            source_labels: [__meta_kubernetes_pod_label_app]
            target_label: app
            regex: (.+)
            replacement: $1
          - action: replace
            source_labels: [__tmp_controller_name]
            target_label: app
            regex: (.+)
            replacement: $1
          # Set a stable 'component' label preferring app.kubernetes.io/component, then component
          - action: replace
            source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_component]
            target_label: component
            regex: (.+)
            replacement: $1
          - action: replace
            source_labels: [__meta_kubernetes_pod_label_component]
            target_label: component
            regex: (.+)
            replacement: $1
          - source_labels: [__meta_kubernetes_pod_node_name]
            action: replace
            target_label: node
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - action: replace
            replacement: $1
            separator: /
            source_labels:
              - __meta_kubernetes_namespace
              - __meta_kubernetes_pod_name
            target_label: pod
          - action: replace
            source_labels:
              - __meta_kubernetes_namespace
            target_label: namespace
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_name
            target_label: instance
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_container_name
            target_label: container
          # Kubernetes 1.24+ often uses containerd logs under /var/log/containers with symlinks
          - action: replace
            separator: /
            regex: "([^/]+)/([^/]+)"
            replacement: /var/log/pods/*$1/$2/*.log
            source_labels:
              - __meta_kubernetes_pod_uid
              - __meta_kubernetes_pod_container_name
            target_label: __path__
          - action: replace
            separator: ;
            regex: "(.+);(.+);(.+)"
            replacement: /var/log/containers/$1_$3_$2-*.log
            source_labels:
              - __meta_kubernetes_pod_name
              - __meta_kubernetes_pod_container_name
              - __meta_kubernetes_namespace
            target_label: __path__
          - source_labels: [__meta_kubernetes_pod_annotationpresent_kubernetes_io_config_hash]
            action: replace
            replacement: true
            target_label: __kubernetes_logs_annotationpresent_kubernetes_io_config_hash 