apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: monitoring
  labels:
    app: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3100"
    spec:
      # This ensures the PVC is accessible by Loki
      securityContext:
        fsGroup: 10001
      containers:
        - name: loki
          image: grafana/loki:2.9.2
          imagePullPolicy: IfNotPresent
          args:
            - -config.file=/etc/loki/loki.yaml
            - -config.expand-env=true
          ports:
            - name: http-metrics
              containerPort: 3100
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/loki
            - name: storage
              mountPath: /data
          resources:
            requests:
              cpu: {{ .Values.loki.resources.requests.cpu | quote }}
              memory: {{ .Values.loki.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.loki.resources.limits.cpu | quote }}
              memory: {{ .Values.loki.resources.limits.memory | quote }}
      volumes:
        - name: config
          configMap:
            name: loki-config
        - name: storage
          persistentVolumeClaim:
            claimName: loki-data 