apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
    spec:
      securityContext:
        fsGroup: 472
        runAsUser: 472
        runAsGroup: 472
      containers:
        - name: grafana
          image: grafana/grafana:10.0.3
          ports:
            - containerPort: 3000
              name: http
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 30
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 60
            timeoutSeconds: 5
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: monitoring-secrets
                  key: grafana-admin-password
            - name: GF_USERS_ALLOW_SIGN_UP
              value: "false"
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "false"
            - name: GF_SECURITY_COOKIE_SECURE
              value: "true"
            - name: GF_SECURITY_COOKIE_SAMESITE
              value: "lax"
            - name: GF_SECURITY_DISABLE_GRAVATAR
              value: "true"
            - name: GF_DASHBOARDS_MIN_REFRESH_INTERVAL
              value: "30s"
            - name: GF_METRICS_ENABLED
              value: "true"
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
            - name: grafana-datasources
              mountPath: /etc/grafana/provisioning/datasources
            - name: grafana-dashboards-config
              mountPath: /etc/grafana/provisioning/dashboards
            - name: grafana-dashboards
              mountPath: /var/lib/grafana/dashboards
          resources:
            requests:
              cpu: {{ .Values.grafana.resources.requests.cpu | quote }}
              memory: {{ .Values.grafana.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.grafana.resources.limits.cpu | quote }}
              memory: {{ .Values.grafana.resources.limits.memory | quote }}
      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-data
        - name: grafana-datasources
          configMap:
            name: grafana-datasources
        - name: grafana-dashboards-config
          configMap:
            name: grafana-dashboards-config
            items:
              - key: dashboards.yaml
                path: dashboards.yaml
        - name: grafana-dashboards
          configMap:
            name: grafana-dashboards-config
            items:
              - key: kubernetes-dashboard.json
                path: kubernetes-dashboard.json
              - key: k8s-cluster-monitoring.json
                path: k8s-cluster-monitoring.json
              - key: node-exporter-dashboard.json
                path: node-exporter-dashboard.json
              - key: nginx-ingress-dashboard.json
                path: nginx-ingress-dashboard.json
              - key: loki-logs-dashboard.json
                path: loki-logs-dashboard.json
              - key: echo-application-dashboard.json
                path: echo-application-dashboard.json 
              - key: prod-overview.json
                path: prod-overview.json
              - key: prod-health.json
                path: prod-health.json
              - key: k6-dashboard.json
                path: k6-dashboard.json