{{- if .Values.ingress.basicAuth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: monitoring-basic-auth
  namespace: monitoring
type: Opaque
data:
  auth: {{ .Values.basicAuthValue | b64enc | quote }}
{{- end }} 