apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: monitoring
  labels:
    app: node-exporter
spec:
  ports:
    - port: 9100
      protocol: TCP
      targetPort: 9100
      name: metrics
  selector:
    app: node-exporter 