---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: do-registry-secret
  namespace: dembrane-web-prod
spec:
  encryptedData:
    .dockerconfigjson: AgB1NmApMe1gyAbidXDgy6EpbpfYqvCjhqc7dfvh7/3kfTjo41SgiI71Wo6RI5GAYcP/ZPOpknyt5Y1CcyOlHgFo2yTFE8DH3HwWjmggSJn35YV5cbbKOYvTc2L+zY1U1+1F6eHLuwatArsA4pLdOvARv7kE4tX8/EAoY2xUtWENOqQWQVG6nKOl9bqkZD/JLeoCBosoOQswNvu2Ge01dZcNqccgh+v5UyJGLycllKf/ZrDHEbVUtAQ3F9Gbq27X2/r9m+nr6vrlW1Zw02AsE/961UsyiQcROkNlULrGqVGVwUhJaqg4X8rcUMxCeNGDAPIiitz3HDZoijRzE6aLUY0lZ2v79kkX4x1reDCPHsRGy6AFrHSBUB5z0auuzJqTlVhLxnoOpZ0c6gmlLxEaF+ylHxBPHNqw9DtApkhuaerH7z0iXiGMnR6sq57cQEqwP37LbCqBU8f1EtxxhXu9p0dm/FStxVW4jzl/4z9zgZ5wMzoG0Itq4nmbWhNPLndKnYQenWS6CsaHcET5FH3ZHAhznjAsyqiBhiqDhNvWbyx/kmaB9xzZjt7jARZWhxUP9PPp4R356EjVYJDX7/72BYyeRDT8JGnQ396QyYUVYiW55jgLzuX0wFdSdO4kW9UFiU7RttCKrDKeMKitkxPx6Uf2GU6HXMpWbYBI9LMJza1MPPhoiZLYlMIHVySTgiRqZQKfCDjEJlWsg8s9/JNZ5lJRCJx07jvwb55z+xuSyk0klURm7JtUEWUZoSp9l8HAqy7VfZ6rIAD9Va9qWNG3d+1oOm3X3Ok6kaCOHx5w2F4zrF5KJm8hcJhqm6sg27ts0meyAtAxNUVcEh3I24M2GYQ8gKAW6mIvRP5cRQPTS0H8tIA6BZnlUMvm5e+ylJHb5uxRi38lcXAJ+KgIKK+n1S0Ce4OhEBvZjPm+VLvzcpLx
  template:
    metadata:
      creationTimestamp: null
      name: do-registry-secret
      namespace: dembrane-web-prod
    type: kubernetes.io/dockerconfigjson
